const { execFileSync } = require("child_process");
const fs = require("fs");
const os = require("os");
const path = require("path");

const { expect } = require("chai");
const dotenv = require("dotenv");
const ethers = require("ethers");

const profiles = require("../helpers/profiles");
const forkNode = require("../helpers/fork-node");
const chain = require("../helpers/chain");
const runner = require("../helpers/scripts");
const signing = require("../helpers/signing");
const lpTimelock = require("../../../scripts/lp-timelock");

/**
 * `LP_APEBOND_MODE=replace-adapter`, rehearsed end to end against a FORK OF LIVE SEPOLIA.
 *
 * ── What this is ──────────────────────────────────────────────────────────────────────
 *
 * Commit "Drop soulZapRequestId from the purchase struct" changed the adapter's signed
 * `PurchaseAuthorization` from 15 fields to 14, which changes its EIP-712 type hash. The
 * adapter live on **Sepolia test stack #5** (`0xc91e4037…`) was compiled against the old
 * struct and can never verify a 14-field signature, and the adapter is REPLACEABLE, not
 * upgradeable. So stack #5 has to run `scripts/deploy-apebond.js` in `replace-adapter` mode —
 * a mode that has never run against a live stack.
 *
 * `DeployApeBond.test.js` proves the mode on MOCKS on an empty node. This suite proves it on
 * stack #5 as it stands at the chain head: its vault proxy, its 300-second timelock, its
 * escrow holding ~9,505 tREAL of bonus funding, its old adapter with the SoulZap seat
 * allowlisted, and NFT 231913 staked by the operator. It forks Sepolia at the head,
 * impersonates the two live seats, and runs the repo's own scripts, unmodified, as child
 * processes:
 *
 *   1. `scripts/deploy-apebond.js`, LP_APEBOND_MODE=replace-adapter, with exactly the
 *      environment the live day uses: the operator as the adapter's guardian, the backend key
 *      `0x9FDf…` as the purchase signer, the SoulZap seat `0x0674…` as the one caller. A new
 *      adapter against the EXISTING escrow, the handover to the timelock, ONE batch of three,
 *      the 300-second wait in chain time, the execute, the post-checks and the record.
 *   2. a static `depositFor` against the NEW adapter, signed by a throwaway key, which must
 *      revert `InvalidSignature(throwaway, 0x9FDf…)` — the adapter answers to the production
 *      key and nothing else.
 *   3. `scripts/set-purchase-signer.js`, the guardian's one undelayed transaction, pointing the
 *      fork's adapter at that throwaway key (see "Why the purchase uses a throwaway key").
 *   4. `scripts/apebond-rehearsal.js`, deposit phase: the SoulZap seat mints a position on the
 *      REAL Uniswap Sepolia position manager, in a range around the pool's current tick, signs
 *      a 14-field authorization, approves the new adapter and calls `depositFor`.
 *   5. the cliff, pushed past with one `evm_increaseTime`, and the rehearsal's claim phase:
 *      the beneficiary is paid exactly the 495 tREAL bonus out of the escrow.
 *
 * ── Why the purchase uses a throwaway key ─────────────────────────────────────────────
 *
 * The replacement runs with the PRODUCTION signer, because that is the command the live day
 * runs and the registry record must say so. But nobody here holds `0x9FDf…`'s private key,
 * and a Hardhat node can send a transaction AS an impersonated account but cannot SIGN typed
 * data for one. So the purchase proof rotates the signer on the fork to a key generated by
 * this suite — through `set-purchase-signer.js`, the same guardian-tier call the live day
 * would use for a key rotation — and phase 2 is the evidence for the production value that
 * can be had without its key: the new adapter recovers every signature against `0x9FDf…` and
 * rejects anything else.
 *
 * ── Opt-in, and NOT a CI gate ─────────────────────────────────────────────────────────
 *
 * The suite runs only when `LP_APEBOND_DRYRUN=1` is set; otherwise its `before` calls
 * `this.skip()` and every case reports as pending, exactly as its sibling
 * `ApeBondUpgradeInPlace.test.js` does. The reason is the fork block: stack #5 was deployed
 * long after every pinned block in this repo, so this suite forks the HEAD, and a head fork is
 * not deterministic (the pool price, the balances and the escrow's funding are whatever
 * Sepolia holds when the node starts). `.github/workflows/ci.yml` never sets the flag.
 *
 * Unlike the sibling, the flag alone is enough: with no `SEPOLIA_RPC_URL` and no
 * `INFURA_API_KEY` the fork is tried against the repo's public Sepolia fallbacks
 * (`profiles.sepolia.rpc.publicCandidates` — tenderly, then publicnode), the same list CI's
 * profile-driven fork suite uses. A fork that cannot be established on ANY candidate FAILS
 * the run: the operator asked for it explicitly, and a skip would read as "nothing wrong".
 *
 *     LP_APEBOND_DRYRUN=1 npx hardhat test test/lp-staking/integration/ApeBondReplaceAdapter.test.js
 *
 * ── The operator's `.env` does not leak into the children ────────────────────────────
 *
 * `hardhat.config.js` loads the repository's `.env` in every child, and the runner only strips
 * `LP_*` from THIS process's environment, so a live-day `.env` in the working tree (a
 * `LP_APEBOND_PURCHASE_SIGNER`, a `LP_REHEARSAL_CALLER_KEY`, an `LP_APEBOND_MODE`) would reach
 * the scripts and change what they do — `set-purchase-signer.js` would refuse a key that does
 * not match the address, the rehearsal would refuse a caller named twice. dotenv never
 * overrides a variable that is already present, so {@link dotenvShield} hands every child an
 * EMPTY value for each key the file defines, unless this suite sets that key itself, and every
 * script here reads an empty value as unset. The file is parsed in memory; no value is printed.
 *
 * ── Nothing in the repository is written ──────────────────────────────────────────────
 *
 * Every child records into `DEPLOYMENTS_FILE`, a scratch copy of the tracked registry with
 * the live stack's entry ALSO recorded under chain 31337, which is what the fork reports. The
 * tracked `deployments.json` and the committed `.openzeppelin/sepolia.json` are compared by
 * sha256 before and after, and `git status --porcelain` must gain no entry over the run.
 */

/** Captured before a single test runs; asserted again at the very end. */
const TRACKED_REGISTRY_SHA256 = runner.sha256File(runner.TRACKED_REGISTRY);

/** The world: Sepolia, at the head rather than at the profile's pinned block. */
const P = profiles.sepolia;

const LIVE_CHAIN_KEY = "11155111";
const FORK_CHAIN_KEY = "31337";
const FORK_CHAIN_ID = 31337;

/** The operator: deployer, the timelock's proposer and executor, and the adapter's guardian. */
const DEPLOYER = ethers.getAddress("0x5576bD37419dadAab305cca998E16BcD73318A35");
/** The backend key the live adapter recovers purchase signatures against. */
const PRODUCTION_PURCHASE_SIGNER = ethers.getAddress("0x9FDf824f8F90c74286fDB1D8865F0223d7797a09");
/** The one SoulZap seat allowlisted on the live adapter (an EOA on Sepolia). */
const SOULZAP_CALLER = ethers.getAddress("0x067480A36c6372f910cC94dF2691D9dA5754c2A0");
/** The adapter this replacement retires: 15-field struct, activated 2026-09-15. */
const LIVE_ADAPTER = ethers.getAddress("0xc91e4037b056696577e6e78e1bAaFd51fC270307");

/** The one live staked position on stack #5, staked by the operator on 2026-09-14. */
const STAKED_TOKEN_ID = "231913";

/**
 * keccak256 of the 14-field `PurchaseAuthorization(...)` type string. Stated as a literal so a
 * drift between the contract, the signing helper and this number fails here.
 */
const TYPEHASH_14_FIELDS = "0x0cdde6e0aef5226848dc423d203f4d89de725dd7dc8dd3ae7329c03336a6ae04";

/** topic0 of `ApeBondPositionDeposited`, 12 inputs, three of them indexed. */
const DEPOSITED_TOPIC0 = "0xe332e98d7f62fb5314f6b37aadd8db22c291c7649df7c504c4f774df778b9093";

/** The sample purchase's bonus, in whole tREAL. Small against the escrow's ~9,505 free. */
const BONUS_WHOLE = "495";

/** The rehearsal's cliff. Short enough to push past with one `evm_increaseTime`. */
const CLIFF_SECONDS = 600;
const CLIFF_PUMP_SECONDS = 601;

/** Fixed top-up for the SoulZap seat from the operator, in whole tokens, before the mint. */
const CALLER_ASSET_WHOLE = 10_000n;
const CALLER_USDC_WHOLE = 2_500n;

/** Plenty of ETH for gas on the fork, for every account this suite sends from. */
const FORK_ETH = ethers.parseEther("10000");

/** Child-process ceilings. A fork at the head is cold, so the first run is the slow one. */
const DEPLOY_TIMEOUT_MS = 20 * 60 * 1000;
const SCRIPT_TIMEOUT_MS = 10 * 60 * 1000;

/** ERC-1967 implementation slot: keccak256("eip1967.proxy.implementation") - 1. */
const ERC1967_IMPLEMENTATION_SLOT =
  "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc";

const VAULT_IFACE = new ethers.Interface([
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function guardian() view returns (address)",
  "function operator() view returns (address)",
  "function zapper() view returns (address)",
  "function twapWindow() view returns (uint32)",
  "function maxTwapDeviationTicks() view returns (uint24)",
  "function depositsPaused() view returns (bool)",
  "function rebalancePaused() view returns (bool)",
  "function stakerOf(uint256 tokenId) view returns (address)",
  "function isStakeOperator(address account) view returns (bool)",
  "function positionManager() view returns (address)",
  "function pool() view returns (address)",
  "function token0() view returns (address)",
  "function token1() view returns (address)",
  "function fee() view returns (uint24)",
  "function setStakeOperator(address account, bool allowed)",
]);

const ESCROW_IFACE = new ethers.Interface([
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function adapter() view returns (address)",
  "function bonusToken() view returns (address)",
  "function totalReserved() view returns (uint256)",
  "function reservationOf(bytes32 purchaseId) view returns (address beneficiary,uint256 amount,uint64 unlockAt,bool claimed)",
  "function claimable(bytes32 purchaseId) view returns (uint256)",
  "function setAdapter(address newAdapter)",
]);

const ADAPTER_IFACE = new ethers.Interface([
  "function owner() view returns (address)",
  "function vault() view returns (address)",
  "function escrow() view returns (address)",
  "function positionManager() view returns (address)",
  "function guardian() view returns (address)",
  "function purchaseSigner() view returns (address)",
  "function depositsPaused() view returns (bool)",
  "function soulZapCallers(address caller) view returns (bool)",
  "function token0() view returns (address)",
  "function token1() view returns (address)",
  "function fee() view returns (uint24)",
  "function PURCHASE_AUTHORIZATION_TYPEHASH() view returns (bytes32)",
  "function eip712Domain() view returns (bytes1 fields, string name, string version, uint256 chainId, address verifyingContract, bytes32 salt, uint256[] extensions)",
  "function hashPurchaseAuthorization((bytes32 purchaseId,bytes32 campaignId,address beneficiary,address soulZapCaller,address inputToken,uint256 grossInputAmount,uint256 netInputAmount,uint256 guaranteedBonusAmount,uint64 bonusUnlockAt,uint128 minLiquidity,int24 expectedTickLower,int24 expectedTickUpper,uint256 nonce,uint256 deadline) authorization) view returns (bytes32)",
  "function depositFor(uint256 tokenId,(bytes32 purchaseId,bytes32 campaignId,address beneficiary,address soulZapCaller,address inputToken,uint256 grossInputAmount,uint256 netInputAmount,uint256 guaranteedBonusAmount,uint64 bonusUnlockAt,uint128 minLiquidity,int24 expectedTickLower,int24 expectedTickUpper,uint256 nonce,uint256 deadline) authorization,bytes realSignature)",
  "error InvalidSignature(address recovered, address expected)",
]);

/** Only the adapter's one event, so a receipt can be decoded without its whole ABI. */
const DEPOSITED_IFACE = new ethers.Interface([
  "event ApeBondPositionDeposited(bytes32 indexed purchaseId,bytes32 indexed campaignId,address indexed beneficiary,uint256 tokenId,uint128 liquidity,int24 tickLower,int24 tickUpper,address inputToken,uint256 grossInputAmount,uint256 netInputAmount,uint256 guaranteedBonusAmount,uint64 bonusUnlockAt)",
]);

const ERC20_IFACE = new ethers.Interface([
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
  "function balanceOf(address) view returns (uint256)",
  "function transfer(address to,uint256 value) returns (bool)",
]);

const NPM_IFACE = new ethers.Interface([
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function positions(uint256 tokenId) view returns (uint96 nonce,address operator,address token0,address token1,uint24 fee,int24 tickLower,int24 tickUpper,uint128 liquidity,uint256 feeGrowthInside0LastX128,uint256 feeGrowthInside1LastX128,uint128 tokensOwed0,uint128 tokensOwed1)",
]);

const POOL_IFACE = new ethers.Interface([
  "function slot0() view returns (uint160 sqrtPriceX96,int24 tick,uint16 observationIndex,uint16 observationCardinality,uint16 observationCardinalityNext,uint8 feeProtocol,bool unlocked)",
]);

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** `git status --porcelain` in the repository this suite runs from, as a set of lines. */
function gitStatus() {
  const out = execFileSync("git", ["status", "--porcelain"], {
    cwd: forkNode.REPO_ROOT,
    encoding: "utf8",
  });
  return new Set(out.split("\n").filter((line) => line.trim() !== ""));
}

/**
 * Runs `fn` while the node's clock is pushed forward, and stops pushing when it returns.
 *
 * The same harness `DeployApeBond.test.js` and `ApeBondUpgradeInPlace.test.js` use:
 * `deploy-apebond.js` waits in CHAIN time, so five seconds of chain time every 150 ms of wall
 * clock clears stack #5's 300-second `minDelay` in about nine seconds. Used for the
 * replacement ONLY — the purchase's one-hour deadline and 600-second cliff must not run at
 * thirty times wall speed while the suite is asserting on them.
 */
async function withTimePump(provider, fn) {
  let running = true;
  const pump = (async () => {
    while (running) {
      try {
        await provider.send("evm_increaseTime", [5]);
        await provider.send("evm_mine", []);
      } catch {
        /* the node is busy; the next tick makes up for it */
      }
      await sleep(150);
    }
  })();

  try {
    return await fn();
  } finally {
    running = false;
    await pump;
  }
}

/**
 * `{KEY: ""}` for every key the repository's `.env` defines, or `{}` when there is no `.env`.
 * Spread UNDER the suite's own values, so what this suite sets always wins.
 */
function dotenvShield() {
  const file = path.join(forkNode.REPO_ROOT, ".env");
  if (!fs.existsSync(file)) return {};
  return Object.fromEntries(Object.keys(dotenv.parse(fs.readFileSync(file))).map((key) => [key, ""]));
}

/** Digs the revert payload out of the several shapes ethers v6 can wrap it in. */
function revertData(error) {
  for (const candidate of [
    error?.data,
    error?.info?.error?.data,
    error?.error?.data,
    error?.error?.error?.data,
  ]) {
    if (typeof candidate === "string" && candidate.startsWith("0x") && candidate.length >= 10) {
      return candidate;
    }
    if (candidate && typeof candidate.data === "string" && candidate.data.startsWith("0x")) {
      return candidate.data;
    }
  }
  return null;
}

describe("ApeBond adapter replacement, rehearsed on a fork of live Sepolia (stack #5)", function () {
  // A cold fork of the chain head, four script children, one real Uniswap mint and a timelock
  // batch waited out in chain time.
  this.timeout(45 * 60 * 1000);

  // ── run state ───────────────────────────────────────────────────────────
  let node = null;
  let provider = null;
  let scratchDir = null;
  let registryFile = null;
  let logFile = null;
  let fees = null;
  let shield = {};
  let rpcUsed = null;
  let forkHead = null;

  let gitStatusAtStart = null;
  let manifestSha256AtStart = null;
  const manifestFile = path.join(forkNode.REPO_ROOT, ".openzeppelin", "sepolia.json");

  /** The live stack, read out of the tracked registry. */
  let live = null;

  let vault, timelock, npm, pool, token0, escrow, oldAdapter, newAdapter;
  let vaultAddress, timelockAddress, escrowAddress, newAdapterAddress;
  let token0Address, token1Address, npmAddress, poolAddress;
  let decimals0;

  let deployerSigner = null;
  let callerSigner = null;
  let beneficiary = null;
  let throwawaySigner = null;

  /** Everything the replacement must leave exactly where it found it, read before it runs. */
  let baseline = null;

  /** Per-phase child-process results, so a later `it` can assert an earlier phase's output. */
  const runs = {};

  /** Everything the summary prints. */
  const summary = { addresses: {}, transactions: {}, facts: {} };

  /** The rehearsal's record file, re-read after each phase. */
  let record = null;

  const at = (address, iface) => new ethers.Contract(address, iface, provider);
  const entry = (kind) => runner.registryEntry(registryFile, FORK_CHAIN_ID, kind);

  async function implementationOf(proxy) {
    const word = await provider.getStorage(proxy, ERC1967_IMPLEMENTATION_SLOT);
    return ethers.getAddress("0x" + word.slice(-40));
  }

  /** Unlocks an account on the fork, gives it gas, and returns a signer that sends as it. */
  async function impersonate(address) {
    const checksummed = ethers.getAddress(address);
    await provider.send("hardhat_impersonateAccount", [checksummed]);
    await provider.send("hardhat_setBalance", [checksummed, ethers.toBeHex(FORK_ETH)]);
    return chain.pinFees(new ethers.JsonRpcSigner(provider, checksummed), fees);
  }

  /** Pushes chain time forward by `seconds` and mines one block, once. */
  async function pumpTime(seconds) {
    await provider.send("evm_increaseTime", [seconds]);
    await provider.send("evm_mine", []);
  }

  /** The vault fields the replacement must not move. */
  async function vaultState() {
    return {
      implementation: await implementationOf(vaultAddress),
      owner: ethers.getAddress(await vault.owner()),
      pendingOwner: ethers.getAddress(await vault.pendingOwner()),
      guardian: ethers.getAddress(await vault.guardian()),
      operator: ethers.getAddress(await vault.operator()),
      zapper: ethers.getAddress(await vault.zapper()),
      twapWindow: Number(await vault.twapWindow()),
      maxTwapDeviationTicks: Number(await vault.maxTwapDeviationTicks()),
      depositsPaused: await vault.depositsPaused(),
      rebalancePaused: await vault.rebalancePaused(),
      staker: ethers.getAddress(await vault.stakerOf(STAKED_TOKEN_ID)),
      nftOwner: ethers.getAddress(await npm.ownerOf(STAKED_TOKEN_ID)),
      distributorImplementation: await implementationOf(live.RewardsDistributor.address),
    };
  }

  /** A sample 14-field authorization from the SoulZap seat, valid for an hour of chain time. */
  async function sampleAuthorization() {
    const now = (await provider.getBlock("latest")).timestamp;
    return {
      purchaseId: ethers.id(`replace-adapter-dryrun-static-${now}`),
      campaignId: ethers.id("REAL-APEBOND-REHEARSAL"),
      beneficiary,
      soulZapCaller: SOULZAP_CALLER,
      inputToken: token1Address,
      grossInputAmount: 10_000n * 10n ** 6n,
      netInputAmount: 9_900n * 10n ** 6n,
      guaranteedBonusAmount: ethers.parseUnits(BONUS_WHOLE, decimals0),
      bonusUnlockAt: BigInt(now + CLIFF_SECONDS),
      minLiquidity: 1n,
      expectedTickLower: -60,
      expectedTickUpper: 60,
      nonce: BigInt(now),
      deadline: BigInt(now + 3600),
    };
  }

  /** The environment every child gets: the node, the scratch registry, and nothing else. */
  function baseEnv(extra = {}) {
    return {
      ...shield,
      LOCALHOST_RPC_URL: node.rpcUrl,
      LOCALHOST_GAS_PRICE: String(fees.maxFeePerGas),
      DEPLOYMENTS_FILE: registryFile,
      ...extra,
    };
  }

  /** Runs one script and refuses a non-zero exit, with the child's own output in the error. */
  async function runOk(script, extra, { timeoutMs = SCRIPT_TIMEOUT_MS, pump = false } = {}) {
    const invoke = () =>
      runner.runHardhatScript(`scripts/${script}`, baseEnv(extra), { logFile, timeoutMs });
    const result = pump ? await withTimePump(provider, invoke) : await invoke();
    if (result.code !== 0) {
      throw new Error(
        `scripts/${script} exited ${result.code}\n--- stdout ---\n${result.stdout}\n` +
          `--- stderr ---\n${result.stderr}`
      );
    }
    return result;
  }

  // ─────────────────────────────────────────────────────────────
  before(async function () {
    // ── The opt-in gate. The only place a skip is legal. ─────────────────────────────
    if (process.env.LP_APEBOND_DRYRUN !== "1") {
      console.warn(
        "\n  [apebond-replace-dryrun] skipping — this suite rehearses the ApeBond adapter\n" +
          "  replacement against a fork of live Sepolia at the CHAIN HEAD, which is not\n" +
          "  deterministic and is therefore not a CI gate. Ask for it explicitly:\n" +
          "    LP_APEBOND_DRYRUN=1 npx hardhat test " +
          "test/lp-staking/integration/ApeBondReplaceAdapter.test.js\n"
      );
      this.skip();
      return;
    }

    gitStatusAtStart = gitStatus();
    manifestSha256AtStart = runner.sha256File(manifestFile);

    shield = dotenvShield();
    if (Object.keys(shield).length > 0) {
      console.log(
        `  [apebond-replace-dryrun] .env found: ${Object.keys(shield).length} variable(s) blanked ` +
          `for the child scripts unless this suite sets them: ${Object.keys(shield).join(", ")}`
      );
    }

    scratchDir = fs.mkdtempSync(path.join(os.tmpdir(), "lp-apebond-replace-"));
    registryFile = path.join(scratchDir, "deployments.json");
    logFile = path.join(scratchDir, "scripts.log");

    // ── The scratch registry: the tracked file, with the live stack ALSO under 31337. ──
    const tracked = JSON.parse(fs.readFileSync(runner.TRACKED_REGISTRY, "utf8"));
    live = tracked[LIVE_CHAIN_KEY];
    expect(live, `deployments.json has no chain ${LIVE_CHAIN_KEY} entry`).to.be.an("object");
    fs.writeFileSync(
      registryFile,
      JSON.stringify({ ...tracked, [FORK_CHAIN_KEY]: live }, null, 2) + "\n"
    );

    // The registry must describe the stack this suite was written against. A registry naming
    // another adapter, signer or seat describes a replacement nobody is going to run.
    expect(ethers.getAddress(live.ApeBondPositionAdapter.address)).to.equal(LIVE_ADAPTER);
    expect(ethers.getAddress(live.ApeBondPositionAdapter.purchaseSigner)).to.equal(
      PRODUCTION_PURCHASE_SIGNER
    );
    expect(live.ApeBondPositionAdapter.soulZapCallers.map(ethers.getAddress)).to.deep.equal([
      SOULZAP_CALLER,
    ]);
    expect(ethers.getAddress(live.ApeBondPositionAdapter.guardian)).to.equal(DEPLOYER);
    expect(ethers.getAddress(live.BonusEscrow.adapter)).to.equal(LIVE_ADAPTER);
    expect(live.TimelockController.proposers.map(ethers.getAddress)).to.include(DEPLOYER);
    expect(live.TimelockController.executors.map(ethers.getAddress)).to.include(DEPLOYER);

    // ── The fork, at the head: the configured endpoint, else the public fallbacks. ────
    const established = await forkNode.establishFork({
      logDir: scratchDir,
      profile: P,
      blockNumber: forkNode.LATEST_BLOCK,
    });
    if (established === null) {
      throw new Error(
        "[apebond-replace-dryrun] LP_APEBOND_DRYRUN=1 asked for this dry-run, but no Sepolia " +
          "fork could be established: no endpoint is configured and every public fallback " +
          `(${P.rpc.publicCandidates.join(", ")}) refused — each one's error is printed ` +
          `above. Reported as a FAILURE, not a skip. Set ${P.rpc.envUrl} and re-run.`
      );
    }
    node = established.node;
    provider = established.provider;
    rpcUsed = established.url;
    forkHead = established.probe.head;
    fees = await chain.derivePinnedFees(provider);

    // ── The seats ────────────────────────────────────────────────────────────────────
    deployerSigner = await impersonate(DEPLOYER);
    callerSigner = await impersonate(SOULZAP_CALLER);
    // A fresh buyer, so "the beneficiary grew by exactly the bonus" has no other explanation.
    beneficiary = ethers.Wallet.createRandom().address;
    // The key the fork's purchase is signed with. Generated here, never written anywhere.
    throwawaySigner = ethers.Wallet.createRandom();

    // ── Bind to the live stack ───────────────────────────────────────────────────────
    vaultAddress = ethers.getAddress(live.LPStakingVault.address);
    timelockAddress = ethers.getAddress(live.TimelockController.address);
    escrowAddress = ethers.getAddress(live.BonusEscrow.address);
    vault = at(vaultAddress, VAULT_IFACE);
    timelock = new ethers.Contract(timelockAddress, lpTimelock.TIMELOCK_INTERFACE, provider);
    escrow = at(escrowAddress, ESCROW_IFACE);
    oldAdapter = at(LIVE_ADAPTER, ADAPTER_IFACE);

    npmAddress = ethers.getAddress(await vault.positionManager());
    poolAddress = ethers.getAddress(await vault.pool());
    token0Address = ethers.getAddress(await vault.token0());
    token1Address = ethers.getAddress(await vault.token1());
    npm = at(npmAddress, NPM_IFACE);
    pool = at(poolAddress, POOL_IFACE);
    token0 = at(token0Address, ERC20_IFACE);
    decimals0 = Number(await token0.decimals());

    // ── The "before" side ────────────────────────────────────────────────────────────
    baseline = {
      vault: await vaultState(),
      minDelay: await timelock.getMinDelay(),
      escrowAdapter: ethers.getAddress(await escrow.adapter()),
      oldIsOperator: await vault.isStakeOperator(LIVE_ADAPTER),
      oldTypehash: await oldAdapter.PURCHASE_AUTHORIZATION_TYPEHASH(),
      oldPurchaseSigner: ethers.getAddress(await oldAdapter.purchaseSigner()),
      oldCallerAllowed: await oldAdapter.soulZapCallers(SOULZAP_CALLER),
      escrowBalance: await token0.balanceOf(escrowAddress),
      totalReserved: await escrow.totalReserved(),
      canPropose: await timelock.hasRole(await timelock.PROPOSER_ROLE(), DEPLOYER),
      canExecute: await timelock.hasRole(await timelock.EXECUTOR_ROLE(), DEPLOYER),
      forkBlock: await provider.getBlockNumber(),
    };

    summary.facts.endpoint = String(rpcUsed).replace(/\/v3\/[^/?#]+/, "/v3/<redacted>");
    summary.facts.forkHead = String(forkHead);
    summary.facts["timelock minDelay"] = `${baseline.minDelay}s`;
    summary.facts["escrow balance (before)"] =
      `${ethers.formatUnits(baseline.escrowBalance, decimals0)} (reserved ${ethers.formatUnits(baseline.totalReserved, decimals0)})`;
    summary.addresses["LPStakingVault (proxy)"] = vaultAddress;
    summary.addresses["LPTimelock"] = timelockAddress;
    summary.addresses["BonusEscrow (proxy)"] = escrowAddress;
    summary.addresses["adapter replaced"] = LIVE_ADAPTER;
    summary.addresses["operator / deployer (impersonated)"] = DEPLOYER;
    summary.addresses["SoulZap seat (impersonated)"] = SOULZAP_CALLER;
    summary.addresses["beneficiary (fresh)"] = beneficiary;
    summary.addresses["throwaway purchase signer"] = throwawaySigner.address;
  });

  after(async function () {
    if (node) await node.stop();
    if (provider) provider.destroy();
    if (Object.keys(summary.addresses).length > 0) printSummary(summary);
    if (scratchDir) fs.rmSync(scratchDir, { recursive: true, force: true });
  });

  // ─────────────────────────────────────────────────────────────
  describe("0. the live stack the fork is standing on", function () {
    it("forks Sepolia ahead of the profile's pinned block", function () {
      expect(forkHead).to.be.greaterThan(P.pinnedBlock);
    });

    it("has the vault owned by the 300-second timelock, driven by the operator", function () {
      expect(baseline.vault.owner).to.equal(timelockAddress);
      expect(baseline.minDelay).to.equal(300n);
      expect(baseline.canPropose).to.equal(true);
      expect(baseline.canExecute).to.equal(true);
    });

    it("runs the old adapter, allowlisted on the vault and named by the escrow", function () {
      expect(baseline.escrowAdapter).to.equal(LIVE_ADAPTER);
      expect(baseline.oldIsOperator).to.equal(true);
      expect(baseline.oldPurchaseSigner).to.equal(PRODUCTION_PURCHASE_SIGNER);
      expect(baseline.oldCallerAllowed).to.equal(true);
    });

    it("has an old adapter that cannot verify the 14-field struct", function () {
      expect(baseline.oldTypehash).to.not.equal(TYPEHASH_14_FIELDS);
    });

    it(`holds NFT ${STAKED_TOKEN_ID}, credited to the operator`, function () {
      expect(baseline.vault.nftOwner).to.equal(vaultAddress);
      expect(baseline.vault.staker).to.equal(DEPLOYER);
    });

    it("has an escrow that can back the sample bonus", function () {
      const free = baseline.escrowBalance - baseline.totalReserved;
      expect(free >= ethers.parseUnits(BONUS_WHOLE, decimals0)).to.equal(true);
    });
  });

  // ─────────────────────────────────────────────────────────────
  describe("1. deploy-apebond.js LP_APEBOND_MODE=replace-adapter — the live-day command", function () {
    let scheduled, executed, batchCalls, batch;

    before(async function () {
      runs.replace = await runOk(
        "deploy-apebond.js",
        {
          LP_DEPLOYER_IMPERSONATE: DEPLOYER,
          LP_APEBOND_MODE: "replace-adapter",
          LP_APEBOND_GUARDIAN: DEPLOYER,
          LP_APEBOND_PURCHASE_SIGNER: PRODUCTION_PURCHASE_SIGNER,
          LP_APEBOND_SOULZAP_CALLERS: SOULZAP_CALLER,
          LP_APEBOND_ASSERT_POSITIONS: STAKED_TOKEN_ID,
          LP_APEBOND_WAIT_POLL_MS: "200",
        },
        { timeoutMs: DEPLOY_TIMEOUT_MS, pump: true }
      );

      newAdapterAddress = ethers.getAddress(entry("ApeBondPositionAdapter").address);
      newAdapter = at(newAdapterAddress, ADAPTER_IFACE);

      batchCalls = JSON.parse(
        fs.readFileSync(path.join(scratchDir, "apebond-replace-adapter-batch.json"), "utf8")
      );
      batch = lpTimelock.buildBatch(batchCalls, "");
      scheduled = await timelock.queryFilter(
        timelock.filters.CallScheduled(batch.id),
        baseline.forkBlock + 1,
        "latest"
      );
      executed = await timelock.queryFilter(
        timelock.filters.CallExecuted(batch.id),
        baseline.forkBlock + 1,
        "latest"
      );

      summary.addresses["ApeBondPositionAdapter (new)"] = newAdapterAddress;
      summary.facts["batch id"] = batch.id;
      summary.transactions["adapter deploy"] = entry("ApeBondPositionAdapter").deployTx;
      if (scheduled.length > 0) summary.transactions["scheduleBatch"] = scheduled[0].transactionHash;
      if (executed.length > 0) summary.transactions["executeBatch"] = executed[0].transactionHash;
    });

    it("says its own post-checks passed, and waited in chain time", function () {
      expect(runs.replace.stdout).to.include("All post-activation checks passed.");
      expect(runs.replace.stdout).to.include("phase 2: SKIPPED");
      expect(runs.replace.stdout).to.include("phase 3: a replacement adapter");
      expect(runs.replace.stdout).to.match(/waiting: -?\d+s of CHAIN time left/);
      expect(runs.replace.stdout).to.include(`LP_DEPLOYER_IMPERSONATE: impersonating ${DEPLOYER}`);
    });

    it("deployed a NEW adapter compiled against the 14-field struct", async function () {
      expect(newAdapterAddress).to.not.equal(LIVE_ADAPTER);
      expect(await provider.getCode(newAdapterAddress)).to.not.equal("0x");
      expect(await newAdapter.PURCHASE_AUTHORIZATION_TYPEHASH()).to.equal(TYPEHASH_14_FIELDS);
      // The signing helper the rehearsal script uses computes the same hash from its field list.
      expect(signing.purchaseAuthorizationTypeHash()).to.equal(TYPEHASH_14_FIELDS);
    });

    it("built ONE batch of exactly the three replacement calls", function () {
      expect(batchCalls).to.deep.equal([
        { target: vaultAddress, fn: "setStakeOperator", args: [LIVE_ADAPTER, "false"] },
        { target: vaultAddress, fn: "setStakeOperator", args: [newAdapterAddress, "true"] },
        { target: escrowAddress, fn: "setAdapter", args: [newAdapterAddress] },
      ]);
    });

    it("scheduled those three calls, and only those, with the 300-second delay", function () {
      expect(scheduled).to.have.lengthOf(3);
      const decoded = scheduled.map((log) => {
        const iface = log.args.target === escrowAddress ? ESCROW_IFACE : VAULT_IFACE;
        const call = iface.parseTransaction({ data: log.args.data });
        return [log.args.target, call.name, ...call.args.map(String)];
      });
      expect(decoded).to.deep.equal([
        [vaultAddress, "setStakeOperator", LIVE_ADAPTER, "false"],
        [vaultAddress, "setStakeOperator", newAdapterAddress, "true"],
        [escrowAddress, "setAdapter", newAdapterAddress],
      ]);
      for (const log of scheduled) expect(log.args.delay).to.equal(300n);
    });

    it("executed the batch only after the delay had passed in chain time", async function () {
      expect(executed).to.have.lengthOf(3);
      expect(await timelock.isOperationDone(batch.id)).to.equal(true);
      const scheduledAt = (await provider.getBlock(scheduled[0].blockNumber)).timestamp;
      const executedAt = (await provider.getBlock(executed[0].blockNumber)).timestamp;
      expect(executedAt - scheduledAt).to.be.at.least(300);
    });

    it("swapped the vault's allowlist entry and re-pointed the escrow", async function () {
      expect(await vault.isStakeOperator(newAdapterAddress)).to.equal(true);
      expect(await vault.isStakeOperator(LIVE_ADAPTER)).to.equal(false);
      expect(ethers.getAddress(await escrow.adapter())).to.equal(newAdapterAddress);
    });

    it("handed the new adapter to the timelock with the live-day configuration", async function () {
      expect(await newAdapter.owner()).to.equal(timelockAddress);
      expect(await newAdapter.guardian()).to.equal(DEPLOYER);
      expect(await newAdapter.purchaseSigner()).to.equal(PRODUCTION_PURCHASE_SIGNER);
      expect(await newAdapter.soulZapCallers(SOULZAP_CALLER)).to.equal(true);
      expect(await newAdapter.depositsPaused()).to.equal(false);
      expect(await newAdapter.vault()).to.equal(vaultAddress);
      expect(await newAdapter.escrow()).to.equal(escrowAddress);
      expect(await newAdapter.positionManager()).to.equal(npmAddress);
      expect(await newAdapter.token0()).to.equal(token0Address);
      expect(await newAdapter.token1()).to.equal(token1Address);
      expect(await newAdapter.fee()).to.equal(3000n);
    });

    it("left the escrow's owner and funding untouched", async function () {
      expect(await escrow.owner()).to.equal(timelockAddress);
      expect(await escrow.pendingOwner()).to.equal(ethers.ZeroAddress);
      expect(await escrow.bonusToken()).to.equal(token0Address);
      expect(await token0.balanceOf(escrowAddress)).to.equal(baseline.escrowBalance);
      expect(await escrow.totalReserved()).to.equal(baseline.totalReserved);
    });

    it(`moved no field of the vault's state, NFT ${STAKED_TOKEN_ID} included`, async function () {
      expect(await vaultState()).to.deep.equal(baseline.vault);
    });

    it("recorded the NEW adapter's own deploy block and transaction", async function () {
      const recorded = entry("ApeBondPositionAdapter");
      const receipt = await provider.getTransactionReceipt(recorded.deployTx);
      expect(receipt.contractAddress).to.equal(newAdapterAddress);
      expect(recorded.block).to.equal(receipt.blockNumber);
      expect(recorded.block).to.be.greaterThan(live.ApeBondPositionAdapter.block);
      expect(recorded.deployTx).to.not.equal(live.ApeBondPositionAdapter.deployTx);
    });

    it("recorded no purchaseSignerTx and no pending keys", function () {
      expect(live.ApeBondPositionAdapter).to.have.property("purchaseSignerTx");
      const recorded = entry("ApeBondPositionAdapter");
      expect(recorded).to.not.have.property("purchaseSignerTx");
      expect(recorded).to.not.have.property("pendingAdapter");
      expect(recorded).to.not.have.property("pendingAdapterBlock");
      expect(recorded).to.not.have.property("pendingAdapterTx");
    });

    it("recorded the signer, callers, guardian and owner THIS run configured", function () {
      const recorded = entry("ApeBondPositionAdapter");
      expect(recorded.address).to.equal(newAdapterAddress);
      expect(recorded.previousAdapter).to.equal(LIVE_ADAPTER);
      expect(recorded.purchaseSigner).to.equal(PRODUCTION_PURCHASE_SIGNER);
      expect(recorded.soulZapCallers).to.deep.equal([SOULZAP_CALLER]);
      expect(recorded.guardian).to.equal(DEPLOYER);
      expect(recorded.owner).to.equal(timelockAddress);
      expect(recorded.vault).to.equal(vaultAddress);
      expect(recorded.escrow).to.equal(escrowAddress);
      expect(recorded.bonusToken).to.equal(token0Address);
      expect(recorded.token0).to.equal(token0Address);
      expect(recorded.token1).to.equal(token1Address);
      expect(recorded.fee).to.equal(3000);
    });

    it("re-pointed the BonusEscrow entry at the new adapter and kept the rest of it", function () {
      expect(entry("BonusEscrow")).to.deep.equal({ ...live.BonusEscrow, adapter: newAdapterAddress });
    });

    it("wrote only the fork's chain key: the 11155111 entry in the copy is untouched", function () {
      const copy = runner.readRegistry(registryFile);
      expect(copy[LIVE_CHAIN_KEY]).to.deep.equal(live);
    });
  });

  // ─────────────────────────────────────────────────────────────
  describe("2. the new adapter answers to the production signer", function () {
    let authorization, domain, signature;

    before(async function () {
      domain = await signing.readEip712Domain(newAdapter);
      authorization = await sampleAuthorization();
      signature = await signing.signPurchaseAuthorization({
        signer: throwawaySigner,
        domain,
        authorization,
      });
    });

    it("signs under the RealApeBondPurchase/1 domain of the NEW adapter", function () {
      expect(domain.name).to.equal("RealApeBondPurchase");
      expect(domain.version).to.equal("1");
      expect(domain.chainId).to.equal(BigInt(FORK_CHAIN_ID));
      expect(domain.verifyingContract).to.equal(newAdapterAddress);
    });

    it("hashes a 14-field authorization exactly as ethers does", async function () {
      const local = ethers.TypedDataEncoder.hash(
        domain,
        { PurchaseAuthorization: signing.PURCHASE_AUTHORIZATION_FIELDS },
        authorization
      );
      expect(signing.PURCHASE_AUTHORIZATION_FIELDS).to.have.lengthOf(14);
      expect(await newAdapter.hashPurchaseAuthorization(authorization)).to.equal(local);
    });

    it("rejects a signature by any other key with InvalidSignature(recovered, 0x9FDf…)", async function () {
      let error = null;
      try {
        await newAdapter.connect(callerSigner).depositFor.staticCall(0n, authorization, signature);
      } catch (caught) {
        error = caught;
      }
      expect(error, "depositFor accepted a signature that is not the purchase signer's").to.not.equal(
        null
      );
      const data = revertData(error);
      expect(data, `no revert data: ${error.shortMessage || error.message}`).to.not.equal(null);
      const parsed = ADAPTER_IFACE.parseError(data);
      expect(parsed.name).to.equal("InvalidSignature");
      expect(parsed.args.recovered).to.equal(throwawaySigner.address);
      expect(parsed.args.expected).to.equal(PRODUCTION_PURCHASE_SIGNER);
    });
  });

  // ─────────────────────────────────────────────────────────────
  describe("3. set-purchase-signer.js — the fork's adapter moves to a key this suite holds", function () {
    before(async function () {
      runs.signer = await runOk("set-purchase-signer.js", {
        LP_DEPLOYER_IMPERSONATE: DEPLOYER,
        LP_APEBOND_PURCHASE_SIGNER_KEY: throwawaySigner.privateKey,
      });
      summary.transactions["setPurchaseSigner (fork only)"] = lastTxHash(runs.signer.stdout);
    });

    it("rotated the NEW adapter's signer through the guardian, without printing the key", async function () {
      expect(runs.signer.stdout).to.include(newAdapterAddress);
      expect(runs.signer.stdout).to.include("The deposit path is OPEN");
      expect(runs.signer.stdout).to.not.include(throwawaySigner.privateKey);
      expect(await newAdapter.purchaseSigner()).to.equal(throwawaySigner.address);
    });
  });

  // ─────────────────────────────────────────────────────────────
  describe("4. apebond-rehearsal.js — one purchase through the new adapter, 14-field struct", function () {
    let tickAtMint, escrowReservedBefore, depositReceipt, depositedLog;

    before(async function () {
      // A fixed top-up from the operator, so the seat's mint budget does not depend on
      // whatever it happens to hold on Sepolia today.
      const asset = CALLER_ASSET_WHOLE * 10n ** BigInt(decimals0);
      const usdc = CALLER_USDC_WHOLE * 10n ** BigInt(await at(token1Address, ERC20_IFACE).decimals());
      await chain.send(token0.connect(deployerSigner).transfer(SOULZAP_CALLER, asset));
      await chain.send(
        at(token1Address, ERC20_IFACE).connect(deployerSigner).transfer(SOULZAP_CALLER, usdc)
      );

      tickAtMint = Number((await pool.slot0()).tick);
      escrowReservedBefore = await escrow.totalReserved();

      // No tick overrides: the script centres the campaign range on the pool's current tick.
      runs.deposit = await runOk("apebond-rehearsal.js", {
        LP_REHEARSAL_CALLER_IMPERSONATE: SOULZAP_CALLER,
        LP_REHEARSAL_BENEFICIARY: beneficiary,
        LP_APEBOND_PURCHASE_SIGNER_KEY: throwawaySigner.privateKey,
        LP_REHEARSAL_CLIFF_SECONDS: String(CLIFF_SECONDS),
        LP_REHEARSAL_BONUS: BONUS_WHOLE,
      });

      record = JSON.parse(
        fs.readFileSync(path.join(scratchDir, `apebond-rehearsal-${FORK_CHAIN_ID}.json`), "utf8")
      );
      depositReceipt = await provider.getTransactionReceipt(record.deposit.depositTx);
      depositedLog = depositReceipt.logs.find(
        (log) =>
          log.address.toLowerCase() === newAdapterAddress.toLowerCase() &&
          log.topics[0] === DEPOSITED_TOPIC0
      );

      summary.facts["pool tick at mint"] = String(tickAtMint);
      summary.facts["campaign range"] = `[${record.tickLower}, ${record.tickUpper}]`;
      summary.facts["position minted"] = record.tokenId;
      summary.facts["purchase id"] = record.purchaseId;
      summary.transactions["mint (real NPM)"] = record.deposit.mintTx;
      summary.transactions["approve new adapter for the NFT"] = record.deposit.approveNftTx;
      summary.transactions["depositFor"] = record.deposit.depositTx;
    });

    it("says the deposit phase passed, as the impersonated SoulZap seat", function () {
      expect(runs.deposit.stdout).to.include("The deposit phase passed");
      expect(runs.deposit.stdout).to.not.include("FAIL");
      expect(runs.deposit.stdout).to.include(
        `LP_REHEARSAL_CALLER_IMPERSONATE: impersonating ${SOULZAP_CALLER}`
      );
      expect(ethers.getAddress(record.soulZapCaller)).to.equal(SOULZAP_CALLER);
    });

    it("went through the NEW adapter, which the registry now names", function () {
      expect(ethers.getAddress(record.adapter)).to.equal(newAdapterAddress);
      expect(ethers.getAddress(record.escrow)).to.equal(escrowAddress);
      expect(ethers.getAddress(record.vault)).to.equal(vaultAddress);
    });

    it("minted a range that contains the pool's current tick, on the REAL position manager", async function () {
      expect(record.tickLower).to.be.at.most(tickAtMint);
      expect(record.tickUpper).to.be.greaterThan(tickAtMint);
      const position = await npm.positions(record.tokenId);
      expect(Number(position.tickLower)).to.equal(record.tickLower);
      expect(Number(position.tickUpper)).to.equal(record.tickUpper);
      expect(position.token0).to.equal(token0Address);
      expect(position.token1).to.equal(token1Address);
      expect(BigInt(position.liquidity)).to.equal(BigInt(record.liquidity));
      expect(BigInt(record.liquidity)).to.be.greaterThan(0n);
    });

    it("gave the VAULT custody and credited the BENEFICIARY, not the caller", async function () {
      expect(await npm.ownerOf(record.tokenId)).to.equal(vaultAddress);
      expect(await vault.stakerOf(record.tokenId)).to.equal(beneficiary);
    });

    it("reserved exactly the bonus in the escrow, unclaimable until the cliff", async function () {
      const bonus = ethers.parseUnits(BONUS_WHOLE, decimals0);
      expect(BigInt(record.guaranteedBonusAmount)).to.equal(bonus);
      const reservation = await escrow.reservationOf(record.purchaseId);
      expect(reservation.beneficiary).to.equal(beneficiary);
      expect(reservation.amount).to.equal(bonus);
      expect(reservation.unlockAt).to.equal(BigInt(record.bonusUnlockAt));
      expect(reservation.claimed).to.equal(false);
      expect(await escrow.totalReserved()).to.equal(escrowReservedBefore + bonus);
      expect(await escrow.claimable(record.purchaseId)).to.equal(0n);
    });

    it(`emitted ApeBondPositionDeposited (topic0 ${DEPOSITED_TOPIC0.slice(0, 10)}…, 12 inputs) from the new adapter`, function () {
      const fragment = DEPOSITED_IFACE.getEvent("ApeBondPositionDeposited");
      expect(fragment.topicHash).to.equal(DEPOSITED_TOPIC0);
      expect(fragment.inputs).to.have.lengthOf(12);
      expect(fragment.inputs.filter((input) => input.indexed)).to.have.lengthOf(3);

      expect(depositedLog, "no ApeBondPositionDeposited log from the new adapter").to.not.equal(
        undefined
      );
      expect(depositedLog.topics).to.have.lengthOf(4);
      const parsed = DEPOSITED_IFACE.parseLog({
        topics: [...depositedLog.topics],
        data: depositedLog.data,
      });
      expect(parsed.args.length).to.equal(12);
      expect({
        purchaseId: parsed.args.purchaseId,
        campaignId: parsed.args.campaignId,
        beneficiary: parsed.args.beneficiary,
        tokenId: parsed.args.tokenId,
        liquidity: parsed.args.liquidity,
        tickLower: Number(parsed.args.tickLower),
        tickUpper: Number(parsed.args.tickUpper),
        inputToken: parsed.args.inputToken,
        grossInputAmount: parsed.args.grossInputAmount,
        netInputAmount: parsed.args.netInputAmount,
        guaranteedBonusAmount: parsed.args.guaranteedBonusAmount,
        bonusUnlockAt: parsed.args.bonusUnlockAt,
      }).to.deep.equal({
        purchaseId: record.purchaseId,
        campaignId: record.campaignId,
        beneficiary,
        tokenId: BigInt(record.tokenId),
        liquidity: BigInt(record.liquidity),
        tickLower: record.tickLower,
        tickUpper: record.tickUpper,
        inputToken: ethers.getAddress(record.inputToken),
        grossInputAmount: BigInt(record.grossInputAmount),
        netInputAmount: BigInt(record.netInputAmount),
        guaranteedBonusAmount: BigInt(record.guaranteedBonusAmount),
        bonusUnlockAt: BigInt(record.bonusUnlockAt),
      });
    });

    it("emitted nothing from the retired adapter", function () {
      const fromOld = depositReceipt.logs.filter(
        (log) => log.address.toLowerCase() === LIVE_ADAPTER.toLowerCase()
      );
      expect(fromOld).to.have.lengthOf(0);
    });
  });

  // ─────────────────────────────────────────────────────────────
  describe("5. the cliff, and the claim for exactly the bonus", function () {
    let beneficiaryBefore, escrowBefore, reservedBefore;

    before(async function () {
      await pumpTime(CLIFF_PUMP_SECONDS);
      beneficiaryBefore = await token0.balanceOf(beneficiary);
      escrowBefore = await token0.balanceOf(escrowAddress);
      reservedBefore = await escrow.totalReserved();
    });

    it(`makes the whole bonus claimable once ${CLIFF_PUMP_SECONDS}s of chain time pass`, async function () {
      expect(await escrow.claimable(record.purchaseId)).to.equal(
        BigInt(record.guaranteedBonusAmount)
      );
    });

    it("pays the beneficiary exactly the bonus out of the escrow", async function () {
      runs.claim = await runOk("apebond-rehearsal.js", {
        LP_REHEARSAL_PHASE: "claim",
        LP_DEPLOYER_IMPERSONATE: DEPLOYER,
      });
      record = JSON.parse(
        fs.readFileSync(path.join(scratchDir, `apebond-rehearsal-${FORK_CHAIN_ID}.json`), "utf8")
      );
      summary.transactions["claim"] = record.claim.tx;

      const bonus = BigInt(record.guaranteedBonusAmount);
      expect(runs.claim.stdout).to.include("The claim phase passed");
      expect((await token0.balanceOf(beneficiary)) - beneficiaryBefore).to.equal(bonus);
      expect(escrowBefore - (await token0.balanceOf(escrowAddress))).to.equal(bonus);
      expect(reservedBefore - (await escrow.totalReserved())).to.equal(bonus);
      expect((await escrow.reservationOf(record.purchaseId)).claimed).to.equal(true);
      expect(await escrow.claimable(record.purchaseId)).to.equal(0n);
    });
  });

  // ─────────────────────────────────────────────────────────────
  describe("6. the repository is exactly as it was", function () {
    it("left the tracked deployments.json byte-identical", function () {
      expect(runner.sha256File(runner.TRACKED_REGISTRY)).to.equal(TRACKED_REGISTRY_SHA256);
    });

    it("left the committed .openzeppelin/sepolia.json byte-identical", function () {
      expect(runner.sha256File(manifestFile)).to.equal(manifestSha256AtStart);
    });

    it("changed nothing git can see", function () {
      expect(
        execFileSync("git", ["status", "--porcelain", "--", "deployments.json", ".openzeppelin"], {
          cwd: forkNode.REPO_ROOT,
          encoding: "utf8",
        })
      ).to.equal("");
      // A set difference: a tree that was already dirty when the suite started is not this
      // run's doing. Run it on a tree nobody else is editing.
      const appeared = [...gitStatus()].filter((line) => !gitStatusAtStart.has(line));
      expect(appeared, `these appeared in git status during the run:\n  ${appeared.join("\n  ")}`)
        .to.deep.equal([]);
    });

    it("wrote every run artifact into the scratch directory instead", function () {
      for (const file of [
        "apebond-replace-adapter-batch.json",
        `apebond-rehearsal-${FORK_CHAIN_ID}.json`,
      ]) {
        expect(fs.existsSync(path.join(scratchDir, file)), `${file} in the scratch dir`).to.equal(
          true
        );
        expect(
          fs.existsSync(path.join(forkNode.REPO_ROOT, file)),
          `${file} must not be in the repository`
        ).to.equal(false);
      }
    });
  });
});

/**
 * The last transaction hash a script printed. `pools.send` logs `  done: <explorer url or
 * hash>` for every transaction it sends, and on chain 31337 there is no explorer, so the
 * hash is printed bare.
 */
function lastTxHash(stdout) {
  const matches = [...stdout.matchAll(/done: .*?(0x[0-9a-fA-F]{64})/g)];
  return matches.length > 0 ? matches[matches.length - 1][1] : null;
}

/** The rehearsal record for the notes: every address and transaction hash, in one block. */
function printSummary({ addresses, transactions, facts }) {
  const rows = [
    ["── fork ──", ""],
    ...Object.entries(facts),
    ["── addresses ──", ""],
    ...Object.entries(addresses),
    ["── transactions (on the fork) ──", ""],
    ...Object.entries(transactions),
  ];
  const width = rows.reduce((max, [label]) => Math.max(max, label.length), 0);
  console.log("\n  ApeBond adapter replacement, fork dry-run — Sepolia test stack #5");
  for (const [label, value] of rows) {
    console.log(`  ${label.padEnd(width)}  ${value === undefined || value === null ? "-" : value}`);
  }
  console.log("");
}
